# Generated by Django 2.2.4 on 2019-08-01 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.IntegerField(default=2, verbose_name='Periodo en minutos')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
        ),
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.IntegerField(null=True, verbose_name='Codigo de estado')),
                ('content_type', models.CharField(max_length=64, verbose_name='Tipo de contenido')),
                ('body', models.TextField(verbose_name='Cuerpo de respuesta')),
            ],
        ),
        migrations.CreateModel(
            name='WebService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL')),
                ('domain', models.CharField(max_length=200, verbose_name='Domain')),
                ('ip', models.GenericIPAddressField(verbose_name='IP')),
                ('last_check', models.DateTimeField(null=True, verbose_name='Ultimo checkpoint')),
            ],
        ),
    ]
