# Generated by Django 2.2.4 on 2019-08-01 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckPeriod',
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='url',
            field=models.URLField(default=None, verbose_name='URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='web_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.WebService'),
        ),
        migrations.AddField(
            model_name='webservice',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='webservice',
            name='minutes',
            field=models.IntegerField(default=2, verbose_name='Intervalo en minutos'),
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='Cuerpo de respuesta'),
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='content_type',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Tipo de contenido'),
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='status_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Codigo de estado'),
        ),
        migrations.AlterField(
            model_name='webservice',
            name='domain',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Domain'),
        ),
        migrations.AlterField(
            model_name='webservice',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='webservice',
            name='last_check',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ultimo checkpoint'),
        ),
    ]
