# Generated by Django 2.2.4 on 2019-08-01 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20190801_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpointerrors',
            name='url',
            field=models.URLField(default='', verbose_name='URL'),
            preserve_default=False,
        ),
    ]
