# Generated by Django 2.2.4 on 2019-08-02 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_checkpointerrors_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpointerrors',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
