# Generated by Django 2.2.4 on 2019-08-02 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_checkpointerrors_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkpointerrors',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='Razon'),
        ),
    ]
