# Generated by Django 2.2.4 on 2019-08-02 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_auto_20190802_0015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkpoint',
            options={'verbose_name': 'Punto de control', 'verbose_name_plural': 'Puntos de control'},
        ),
        migrations.AlterModelOptions(
            name='checkpointerrors',
            options={'verbose_name': 'Error de punto de control', 'verbose_name_plural': 'Errores de punto de control'},
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='date_request',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='checkpointerrors',
            name='date_request',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
    ]
