# Generated by Django 2.2.4 on 2019-08-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_auto_20190802_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='webservice',
            name='slack_api',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
    ]
